version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false

  typescript-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: abstraccion-typescript
    depends_on:
      - jenkins

volumes:
  jenkins_home:
